config/routes.rb
Rails.application.routes.draw do
  root to: "projects#new"
  resources :projects
  resources :tasks do
    get :split, on: :member
  end
  resources :sub_tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  #serializar la semana
  serialize :workingdays,Array
  #asociación
  has_many :tasks, dependent:  :destroy
  #nested
  accepts_nested_attributes_for :tasks

  def workingdays=(value)
    super(value.scan(/\d+/).map(&:to_i))
  end

end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  belongs_to :task, optional: true, class_name: 'Task'
end

app/models/task.rb
class Task < ApplicationRecord
  #asociación
  belongs_to :project
  has_many :subtasks, class_name: 'SubTask', foreign_key: :task_id, dependent: :destroy
  #nested
  accepts_nested_attributes_for :subtasks

  #method split
  def split
    days = project.workingdays
    days.slice!(3..4) if days.include?(6)
    (0..4).each_with_index{|data, index| subtasks << SubTask.new(name: "ST#{index+1}", weekday: days[data % days.size]) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  
  def set_locale
    I18n.config.available_locales = :es
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.tasks.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to task_path(@project.tasks.first.id), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :workingdays, tasks_attributes: [:id, :name, :project_id])
    end
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :set_sub_task, only: [:show, :edit, :update, :destroy]

  # GET /sub_tasks
  # GET /sub_tasks.json
  def index
    @sub_tasks = SubTask.all
  end

  # GET /sub_tasks/1
  # GET /sub_tasks/1.json
  def show
  end

  # GET /sub_tasks/new
  def new
    @sub_task = SubTask.new
  end

  # GET /sub_tasks/1/edit
  def edit
  end

  # POST /sub_tasks
  # POST /sub_tasks.json
  def create
    @sub_task = SubTask.new(sub_task_params)

    respond_to do |format|
      if @sub_task.save
        format.html { redirect_to @sub_task, notice: 'Sub task was successfully created.' }
        format.json { render :show, status: :created, location: @sub_task }
      else
        format.html { render :new }
        format.json { render json: @sub_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_tasks/1
  # PATCH/PUT /sub_tasks/1.json
  def update
    respond_to do |format|
      if @sub_task.update(sub_task_params)
        format.html { redirect_to @sub_task, notice: 'Sub task was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_task }
      else
        format.html { render :edit }
        format.json { render json: @sub_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_tasks/1
  # DELETE /sub_tasks/1.json
  def destroy
    @sub_task.destroy
    respond_to do |format|
      format.html { redirect_to sub_tasks_url, notice: 'Sub task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_task
      @sub_task = SubTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_task_params
      params.require(:sub_task).permit(:name, :weekday, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :split]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def split
    @task.split
    respond_to do |format|
      format.html { redirect_to task_path(@task), notice: 'Split was successfully splited.' }
    end    
  end
  

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <div class="container-fluid">
    <head>
      <title>Sdt</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: 'project_name' %>
  </div>

  <div class="field">
    <b> Días / Semana (Casos)</b><br />
    <%=radio_button_tag 'days', '1', false %> 1-2-3-4-5<br />
    <%=radio_button_tag 'days', '2', false %> 1-2-3<br />
    <%=radio_button_tag 'days', '3', false %> 3-4-5-6-7-1-2
  </div>

  <div class="field">
    <%= form.hidden_field :workingdays,:readonly => true %>
  </div>

  <div class="field">
    <%= form.fields_for :tasks do |formf|  %>
      <%= formf.hidden_field :name, id: 'task_name' %>
    <% end %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>

$( document ).on('turbolinks:load', function() {
  $('input:radio[name="days"]').change(function(){
    if($(this).is(":checked")){
      $("#task_name").val("tarea de " + $("#project_name").val())
      if ($('#days_1').is(':checked')) {
        $("#project_workingdays").val('1,2,3,4,5')
      } else if ($('#days_2').is(':checked')) {
        $("#project_workingdays").val('1,2,3')
      }else{
        $("#project_workingdays").val('3,4,5,6,7,1,2')
      }
    }
  });
})

</script>

app/views/projects/edit.html.erb
<h1>Editando Proyecto <%= @project.name %></h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project, class: 'btn btn-primary' %> |
<%= link_to 'Back', projects_path, class: 'btn btn-primary' %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Workingdays</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.workingdays %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>Nuevo Proyecto</h1>

<%= render 'form', project: @project %>
<br />
<%= link_to 'Back', projects_path, class: 'btn btn-primary' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Workingdays:</strong>
  <%= @project.workingdays %>
</p>

<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %>
<%= link_to 'Back', projects_path, class: 'btn btn-primary' %>

app/views/sub_tasks/_form.html.erb
<%= form_with(model: sub_task, local: true) do |form| %>
  <% if sub_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_task.errors.count, "error") %> prohibited this sub_task from being saved:</h2>

      <ul>
      <% sub_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :weekday %>
    <%= form.number_field :weekday %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_tasks/edit.html.erb
<h1>Editando Sub Task</h1>

<%= render 'form', sub_task: @sub_task %>

<%= link_to 'Show', @sub_task, class: 'btn btn-primary' %> |
<%= link_to 'Back', sub_tasks_path, class: 'btn btn-primary' %>

app/views/sub_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weekday</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_tasks.each do |sub_task| %>
      <tr>
        <td><%= sub_task.name %></td>
        <td><%= sub_task.weekday %></td>
        <td><%= sub_task.task %></td>
        <td><%= link_to 'Show', sub_task %></td>
        <td><%= link_to 'Edit', edit_sub_task_path(sub_task) %></td>
        <td><%= link_to 'Destroy', sub_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Task', new_sub_task_path, class: 'btn btn-primary' %>

app/views/sub_tasks/new.html.erb
<h1>New Sub Task</h1>

<%= render 'form', sub_task: @sub_task %>

<%= link_to 'Back', sub_tasks_path, class: 'btn btn-primary'  %>

app/views/sub_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_task.name %>
</p>

<p>
  <strong>Weekday:</strong>
  <%= @sub_task.weekday %>
</p>

<p>
  <strong>Task:</strong>
  <%= @sub_task.task %>
</p>

<%= link_to 'Edit', edit_sub_task_path(@sub_task), class: 'btn btn-primary'  %>
<%= link_to 'Back', sub_tasks_path, class: 'btn btn-primary'  %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editando <%= @task.name %></h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %>
<%= link_to 'Back', tasks_path, class: 'btn btn-primary'  %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.project_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path, class: 'btn btn-primary'  %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: 'btn btn-primary'  %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>
<%# Falta Prolijidad por tiempo %>
<% if @task.subtasks.present? %>
  <h3>Sub Tareas</h3>  
  <table class="table">
    <thead>
      <% if @task.subtasks.first.weekday == 3 %>
        <tr>
          <th scope="col">Miércoles</th>
          <th scope="col">Jueves</th>
          <th scope="col">Viernes</th>
          <th scope="col">Sábado</th>
          <th scope="col">Domingo</th>
          <th scope="col">Lunes</th>
          <th scope="col">Martes</th>
        </tr>
      <% else %>
        <tr>
          <th scope="col">Lunes</th>
          <th scope="col">Martes</th>
          <th scope="col">Miércoles</th>
          <th scope="col">Jueves</th>
          <th scope="col">Viernes</th>>
        </tr>
      <% end %>
    </thead>
    <tbody>
    <% if @task.subtasks.first.weekday == 3 %>
      <% @task.subtasks.order(:id).each do |st| %>
        <tr>
          <td><%= st.name if st.weekday == 3 %></td>
          <td><%= st.name if st.weekday == 4 %></td>
          <td><%= st.name if st.weekday == 5 %></td>
          <td><%= st.name if st.weekday == 6 %></td>
          <td><%= st.name if st.weekday == 7 %></td>
          <td><%= st.name if st.weekday == 1  %></td>
          <td><%= st.name if st.weekday == 2 %></td>
        </tr>
      <% end %>
    <% else %>
      <% @task.subtasks.order(:id).each do |st| %>
        <tr>
          <td><%= st.name if st.weekday == 1 %></td>
          <td><%= st.name if st.weekday == 2 %></td>
          <td><%= st.name if st.weekday == 3 %></td>
          <td><%= st.name if st.weekday == 4 %></td>
          <td><%= st.name if st.weekday == 5 %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% end %>
<br />
<%= link_to 'Split', split_task_path(@task), class: 'btn btn-info' unless @task.subtasks.present? %>
<%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary' %>
<%= link_to 'Back', tasks_path, class: 'btn btn-primary' %>